[0m14:57:15.002786 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79ec8279c100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79ec82142bf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79ec8143fca0>]}


============================== 14:57:15.008653 | 5320dd65-a858-4678-b63b-a2bb895eb6a9 ==============================
[0m14:57:15.008653 [info ] [MainThread]: Running with dbt=1.8.0-b3
[0m14:57:15.009181 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/teddy/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init data_warehouse', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:57:15.014733 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/home/teddy/.dbt')}
[0m14:57:15.015513 [info ] [MainThread]: Creating dbt configuration folder at 
[0m14:57:15.017351 [debug] [MainThread]: Starter project path: /home/teddy/.local/lib/python3.10/site-packages/dbt/include/starter_project
[0m14:57:15.020874 [info ] [MainThread]: 
Your new dbt project "data_warehouse" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:57:15.021901 [info ] [MainThread]: Setting up your profile.
[0m14:57:15.023595 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m14:57:15.026487 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 0.06288469, "process_user_time": 0.790835, "process_kernel_time": 0.051923, "process_mem_max_rss": "74068", "process_in_blocks": "216", "process_out_blocks": "64", "command_success": false}
[0m14:57:15.028058 [debug] [MainThread]: Command `dbt init` failed at 14:57:15.027901 after 0.06 seconds
[0m14:57:15.028685 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79ec8279c100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79ec8146c7c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79ec8143e6e0>]}
[0m14:57:15.029533 [debug] [MainThread]: Flushing usage events
[0m16:42:39.768557 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71ecd58e40a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71ecd47425c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71ecd4743820>]}


============================== 16:42:39.771056 | 5770edaa-9c1b-42b7-a277-64f7df0c497f ==============================
[0m16:42:39.771056 [info ] [MainThread]: Running with dbt=1.8.0-b3
[0m16:42:39.771530 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/teddy/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt docs generate', 'send_anonymous_usage_stats': 'True'}
[0m16:42:39.772026 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/teddy/Documents/TenX/Week2/DatawarehouseTechStack/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:42:39.772802 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_wall_clock_time": 0.045273386, "process_user_time": 0.768844, "process_kernel_time": 0.071705, "process_mem_max_rss": "73812", "process_out_blocks": "16", "command_success": false, "process_in_blocks": "0"}
[0m16:42:39.773442 [debug] [MainThread]: Command `dbt docs generate` failed at 16:42:39.773356 after 0.05 seconds
[0m16:42:39.773788 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71ecd58e40a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71ecd4743010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71ecd4742ce0>]}
[0m16:42:39.774120 [debug] [MainThread]: Flushing usage events
